name: Build APT repo

on:
  release:
    types: [released]

permissions:
  contents: write
  
jobs:
  repo:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          echo "ok"
